### ISSUE TITLE
All handlers have hard coded 'localhost'

### ISSUE THREAD

**Issue by matttrach** [lean-delivery/ansible-role-jenkins#62]
##### SUMMARY

"Wait for Jenkins" and "Wait for Jenkins with HTTPS" handlers are hardcoded to 'localhost'
For remote installation this means that these handlers will never get a positive status. 
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Handlers
"Wait for Jenkins" and "Wait for Jenkins with HTTPS"
##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]
```

##### CONFIGURATION

none
##### STEPS TO REPRODUCE

Install on remote host rather than localhost

```yaml
---
- hosts: jenkins
  gather_facts: true
  become: true
  tasks:
    - name: Install Java
      import_role:
        name: lean_delivery.java
      vars:
        transport: repositories
        java_major_version: 8

    - name: Install Jenkins
      import_role:
        name: lean_delivery.jenkins
      vars:
        jenkins2_ssh_keys_generate: true
        jenkins2_ssh_keys_slave_hosts: []
        jenkins2_home_directory: /var/lib/jenkins
        jenkins2_cli_username: admin
        jenkins2_cli_password: admin
        jenkins2_release_line: stable
        jenkins2_smtp_enabled: false
        jenkins2_credentials_enabled: true
        jenkins2_credentials:
          jenkinshttpconnectionuser:
            type: password
            id: Jenkins_http_connection
            description: 'for connection via jenkins cli'
            username: "{{ jenkins2_cli_username }}"
            password: "{{ jenkins2_cli_password }}"
```

##### EXPECTED RESULTS

Restart handlers validate Jenkins restart
##### ACTUAL RESULTS

Restart handlers time out, but are ignored

```
ansible-playbook playbook.yml
```
