### ISSUE TITLE
Provide switches and mods to allow for systems without internet access

### ISSUE THREAD

**Issue by ljkimmel** [lean-delivery/ansible-role-jenkins#69]
This is a really good and extensive role but it is fully dependent upon internet access to work. The ability to disable items that require internet would be good. Otherwise, allowing to point to local files for the required items.

**Comment by tgadiev** [comment]
@ljkimmel good idea!

Can you provide any additional details?

**Comment by ljkimmel** [comment]
Sure. For example your `jenkins_epel_url`, `jenkins_rpm_repo_key` and `jenkins_rpm_repo_url` are all statically defined in var/{{ansible_distribution}}.yml but you don't allow for them to be overrridden. Perhaps define them in {{ansible_distribution}}.yml with the leading double underscore (e.g. `__jenkins_epel_url`) and add logic to main.yml to use `set_fact` to override the value when one is provided in `group_vars` or `host_vars` using logic like this:
```
- name: Define jenkins_epel_url
  set_fact:
    jenkins_epel_url: "{{ __jenkins_epel_url }}"
  when: jenkins_epel_url is not defined
```
Also, I suppose people could configure PIP in offline environments to point to a locally configured repository but possibly you could add a task to take a URL as a variable and configure a custom/local repository in PIP for the user.
