### ISSUE TITLE
params bitbucket_project.username,password does not apply

### ISSUE THREAD

**Issue by vkhashkovsky** [lean-delivery/ansible-role-jenkins#71]
##### SUMMARY

params bitbucket_project.username,password does not apply

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
ansible 2.9.10
  config file = None
  configured module search path = ['/Users/xaw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.4 (default, Jul 14 2020, 02:58:48) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### OS / ENVIRONMENT

n/a
##### STEPS TO REPRODUCE

```yaml
 roles:
    - role: lean_delivery.jenkins
      jenkins2_ssh_keys_generate: true
      jenkins2_bitbucket_project_enabled: true
      jenkins2_jira_enabled: true
      jenkins2_smtp_enabled: false
      jenkins2_plugins_list:
        - bitbucket-oauth
        - atlassian-bitbucket-server-integration
      bitbucket_project:
        type: 'password'
        id: 'bitbucket_project'
        description: 'username and password for bitbucket project'
        username: 'tech'
        password: 'test_password'
```

##### EXPECTED RESULTS

Install correct username/password in Global Credentials

##### ACTUAL RESULTS

After installation in Jenkin's Global Credentials contains "bitbucketProjectUser" (default value)

```

```
