### ISSUE TITLE
Wait for Jenkins handler fails on Ansible 2.10

### ISSUE THREAD

**Issue by weakcamel** [lean-delivery/ansible-role-jenkins#72]
##### SUMMARY

Fresh install using the latest released version of ansible-role-jenkins fails. while waiting for Jenkins to come up.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-role-jenkins

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.10.3
  config file = /Users/waldekm/git/auto/ansible.cfg
  configured module search path = ['/Users/waldekm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/waldekm/git/auto/.venv/lib/python3.8/site-packages/ansible
  executable location = /Users/waldekm/git/auto/.venv/bin/ansible
  python version = 3.8.6 (default, Oct 27 2020, 08:57:44) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
[DEPRECATION WARNING]: ALLOW_WORLD_READABLE_TMPFILES option, moved to a per
plugin approach that is more flexible. , use mostly the same config will work,
but now controlled from the plugin itself and not using the general constant.
instead. This feature will be removed in version 2.14. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
ALLOW_WORLD_READABLE_TMPFILES(/Users/weakcamel/git/auto/ansible.cfg) = True
ANSIBLE_COW_SELECTION(/Users/weakcamel/git/auto/ansible.cfg) = stegosaurus
ANSIBLE_FORCE_COLOR(/Users/weakcamel/git/auto/ansible.cfg) = True
ANSIBLE_NOCOWS(/Users/weakcamel/git/auto/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/weakcamel/git/auto/ansible.cfg) = ['/Users/weakcamel/git/auto/galaxy-roles']
DEFAULT_FORKS(/Users/weakcamel/git/auto/ansible.cfg) = 20
DEFAULT_LOG_PATH(/Users/weakcamel/git/auto/ansible.cfg) = /Users/weakcamel/git/auto/log_ansible.txt
DEFAULT_MANAGED_STR(/Users/weakcamel/git/auto/ansible.cfg) = This file is being managed with Ansible. Do NOT update it manually.
DEFAULT_ROLES_PATH(/Users/weakcamel/git/auto/ansible.cfg) = ['/Users/weakcamel/git/auto/galaxy-roles', '/Users/weakcamel/git/auto/roles', '/Users/weakcamel/git/auto/galaxy-roles/languages.codex/languages.codex/playbooks/roles']
DEFAULT_TRANSPORT(/Users/weakcamel/git/auto/ansible.cfg) = ssh
DISPLAY_SKIPPED_HOSTS(/Users/weakcamel/git/auto/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/weakcamel/git/auto/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/weakcamel/git/auto/ansible.cfg) = /usr/bin/python3
INVENTORY_ENABLED(/Users/weakcamel/git/auto/ansible.cfg) = ['auto', 'vmware_vm_inventory', 'yaml', 'host_list']

```

##### OS / ENVIRONMENT

Running Ansible from MacOS against a Ubuntu 18.04 host.

##### STEPS TO REPRODUCE

Playbook ran with:
```
$ ansible-playbook -i inventory/all.yml playbooks/jenkins.yml -vv
```

Playbook content:
```yaml
- name: Install Jenkins server
  hosts: jenkins
  become: true
  vars:
    jenkins2_ssh_keys_generate: true
  tasks:
    - include_role:
        name: lean_delivery.java
      vars:
        java_distribution: openjdk
        java_major_version: 8
        transport: repositories
    - include_role:
        name: lean_delivery.jenkins
      vars:
        jenkins2_plugins_list:
          - gitlab-plugin
          - greenballs
          - azure-ad
          - vsphere-cloud
          - git-parameter
          - rebuild
          - validating-string-parameter
          - parameterized-trigger
          - hashicorp-vault-plugin
          - build-name-setter
          - extensible-choice-parameter
```

Content of `requirements.yml`:

```yaml
---
- src: lean_delivery.jenkins
  version: 2.3.0
- src: lean_delivery.java
  version: 7.0.0
```

##### EXPECTED RESULTS

Successful installation (all OK tasks).

##### ACTUAL RESULTS

```
TASK [lean_delivery.jenkins : Delete user directory] ********************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/configure/Debian.yml:29
changed: [jenkins-test.mydomain.com] => {"changed": true, "path": "/var/lib/jenkins/users/admin", "state": "absent"}

RUNNING HANDLER [lean_delivery.jenkins : Restart Jenkins] ***************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/handlers/main.yml:3
NOTIFIED HANDLER lean_delivery.jenkins : Wait for Jenkins for jenkins-test.mydomain.com
changed: [jenkins-test.mydomain.com] => (...)  "WatchdogUSec": "0"}}

RUNNING HANDLER [lean_delivery.jenkins : Wait for Jenkins] **************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/handlers/main.yml:18
fatal: [jenkins-test.mydomain.com]: FAILED! => {"msg": "The conditional check 'login_page.status == 200' failed. The error was: error while evaluating conditional (login_page.status == 200): 'dict object' has no attribute 'status'"}
```

On re-run:

```
...
TASK [lean_delivery.jenkins : Jenkins confuguration] ********************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/main.yml:114
skipping: [jenkins-test.mydomain.com] => (item=/Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/configure/Debian.yml)  => {"ansible_loop_var": "platform", "changed": false, "platform": "/Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/configure/Debian.yml", "skip_reason": "Conditional result was False"}

TASK [lean_delivery.jenkins : include_tasks] ****************************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/main.yml:125
redirecting (type: modules) ansible.builtin.jenkins_script to community.general.jenkins_script
redirecting (type: modules) ansible.builtin.jenkins_script to community.general.jenkins_script
redirecting (type: modules) ansible.builtin.jenkins_plugin to community.general.jenkins_plugin
included: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/install_plugins.yml for jenkins-test.mydomain.com

TASK [lean_delivery.jenkins : Proxy Configuration] **********************************************************************************************************************************************************
task path: /Users/weakcamel/git/auto/galaxy-roles/lean_delivery.jenkins/tasks/install_plugins.yml:2
redirecting (type: modules) ansible.builtin.jenkins_script to community.general.jenkins_script
fatal: [jenkins-test.mydomain.com]: FAILED! => {"changed": false, "msg": "HTTP error 401 HTTP Error 401: Unauthorized", "output": ""}

PLAY RECAP **************************************************************************************************************************************************************************************************
jenkins-test.mydomain.com : ok=30   changed=0    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0
```
