### ISSUE TITLE
Cannot change username/password

### ISSUE THREAD

**Issue by mehrenreich** [lean-delivery/ansible-role-jenkins#76]
##### SUMMARY

After a successful installation, it's not possible to change `jenkins2_cli_username` or `jenkins2_cli_password` or  Ansible stops with the error message:
```
TASK [lean_delivery.jenkins : Proxy Configuration] ***********************************************************************************************************************************************************************************
fatal: [192.168.9.179]: FAILED! => {"changed": false, "msg": "HTTP error 401 HTTP Error 401: Unauthorized", "output": ""}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Don't know how to fill this.

##### ANSIBLE VERSION

```
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/mike/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mike/.local/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### OS / ENVIRONMENT

Both Ubuntu 18.04.

##### STEPS TO REPRODUCE

First run this:

```yaml
    - role: lean_delivery.jenkins
      vars:
        jenkins2_configure_by_groovy: true
        jenkins2_configure_by_casc: false
```

then this:

```yaml
    - role: lean_delivery.jenkins
      vars:
        jenkins2_configure_by_groovy: true
        jenkins2_configure_by_casc: false
        jenkins2_cli_username: something_else
        jenkins2_cli_password: something_else
```

##### EXPECTED RESULTS

A successful change or username and password.

##### ACTUAL RESULTS

```
fatal: [X.X.X.X]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "args": null,
            "force_basic_auth": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "script": "def host = ''\ndef port = 0\ndef username = ''\ndef password = ''\ndef noProxyHosts = ''\n\nif (host != \"\") {\n    def proxy = new hudson.ProxyConfiguration(host, port, username, password, noProxyHosts)\n    proxy.save()\n    jenkins.model.Jenkins.instance.proxy = proxy\n} else {\n    def xmlFile = hudson.ProxyConfiguration.xmlFile\n    xmlFile.delete()\n    jenkins.model.Jenkins.instance.proxy = null\n}\n",
            "timeout": 240,
            "url": "http://0.0.0.0:8080",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "user": "admin",
            "validate_certs": false
        }
    },
    "msg": "HTTP error 401 HTTP Error 401: Unauthorized",
    "output": ""
}
```
