### ISSUE TITLE
jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator

### ISSUE THREAD

**Issue by patsevanton** [lean-delivery/ansible-role-jenkins#79]
##### SUMMARY
Apply JCasC configuration:
`jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.13.2]
  config file = /home/user/github/infrastructure-as-a-code-example/jenkins-lean-delivery/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```yaml
- name: "Deploy java, jenkins"
  hosts: jenkins
  become: true
  roles:
    - role: lean_delivery.java
      java_major_version: 11
      transport: repositories
    - role: lean_delivery.jenkins
```

##### ACTUAL RESULTS

```
TASK [lean_delivery.jenkins : Apply JCasC configuration] ***************************************************************************************
Воскресенье 31 июля 2022  19:48:14 +0600 (0:00:02.944)       0:12:20.811 ****** 
fatal: [jenkins]: FAILED! => changed=true 
  failed_when_result: true
  output: |-
    Result: {"changed":true,"failed":true,"msg":"io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator"}
```

```

```
