### ISSUE TITLE
Rerun with added plugins doesn't install them

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-jenkins#8]
##### SUMMARY
Rerun with added plugins doesn't install them. See steps to reproduce.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
ansible 2.6.3

##### OS / ENVIRONMENT
RHEL 7.5

##### STEPS TO REPRODUCE
run 1st time:
```yaml
---
- name: Install and Configure Jenkins
  hosts: jenkins
  roles:
    - role: "../../roles/lean_delivery.java"
    - role: "../../roles/ansible-role-jenkins"
```

run 2nd time:
```yaml
---
- name: Install and Configure Jenkins
  hosts: jenkins
  roles:
    - role: "../../roles/lean_delivery.java"
    - role: "../../roles/ansible-role-jenkins"
      jenkins2_plugins_list:
        - sonar
```
2nd run doesn't install additional (sonar) plugin.
